{% set name = "pyrfr" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cdc92b6054a351b85cc7496a2fc86e3192a9d04a92fd6bfa4aa629af360a6d1d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - swig >3.0.0
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - pyrfr
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pyrfr/
  license: BSD-2-Clause AND BSD-3-Clause AND BSL-1.0 AND JSON AND MIT
  license_family: BSD
  license_file:
    - include/cereal/external/rapidxml/license.txt
    - LICENSE_cereal-1.2.2
    - LICENSE_doxy2swig
    - LICENSE.txt
    - LICENSE_rapidjson
    - LICENSE_rapidxml
  summary: An extensible C++ library for random forests with Python bindings.
  description: An extensible C++ library for random forests with Python bindings with a BSD3 license.
  dev_url: https://github.com/automl/random_forest_run
  doc_url: https://automl.github.io/random_forest_run/

extra:
  recipe-maintainers:
    - BastianZim
    - mfeurer
